name: cast2
description: "Ultimate Web Video Caster App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: any
  video_player: any
  media_cast: any # المكتبة البديلة الحديثة والمستقرة للبث والكاست
  file_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
