// إجبار المشروع وكل الحزم (بما فيها file_picker) على البناء باستخدام إصدار 36
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            project.android {
                compileSdkVersion 36
                
                // تأمين توافق إصدارات أدوات البناء
                buildToolsVersion "36.0.0"
            }
        }
    }
}
