buildscript {
    // تم تحديث إصدار الكوتلن ليتوافق مع أندرويد 36 ويحل تحذير KGP السابق
    ext.kotlin_version = '1.9.24' 
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // تم تحديث إصدار الجريدل ليدعم البناء بإصدار SDK 36
        classpath 'com.android.tools.build:gradle:8.3.2' 
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
