name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # سكريبت ذكي يقوم بتحديث الـ Embedding تلقائياً داخل الملفات دون تدخلك
      - name: Fix Android v1 embedding automatically
        run: |
          find . -name "AndroidManifest.xml" -exec sed -i '/<\/application>/i \        <meta-data android:name="flutterEmbedding" android:value="2" \/>' {} \;

      - name: Install dependencies
        run: flutter pub get

      - name: Clean project cache
        run: flutter clean

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
